comment:
  behavior: default
  layout: reach,diff,flags,tree,reach
  show_carryforward_flags: false
coverage:
  range: 70..100
  round: down
  precision: 2
  status:
    changes: false
    project: true
ignore:
  - "Tests"