name: curtz-ios
options:
  bundleIdPrefix: com.sanctumlabs
targets:
  Curtz:
    type: framework
    platform: macOS
    sources: 
      - path: Sources/Curtz
        createIntermediateGroups: true
  CurtziOSApp:
    type: application
    platform: iOS
    deploymentTarget:
      iOS: 15.5
    info:
      path: Sources/CurtziOSApp/Info.plist
    sources: 
      - path: Sources/CurtziOSApp
        excludes: Sources/CurtziOSApp/Info.plist
        createIntermediateGroups: true
    dependencies:
      - target: Curtz
