name: curtz-ios
options:
  bundleIdPrefix: com.sanctumlabs
targets:
  Curtz:
    type: framework
    platform: [iOS, macOS]
    deploymentTarget:
      iOS: 16.0
      macOS: 12.6
    info:
      path: Sources/Curtz/Info.plist
    sources: 
      - path: Sources/Curtz
        createIntermediateGroups: true
    scheme:
      testTargets:
        - CurtzUnitTests
      gatherCoverageData: true
      coverageTargets:
        - Curtz_macOS
  CurtzUnitTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: 12.6
    info:
      path: Tests/Curtz/Info.plist
    sources:
      - path: Tests/Curtz
        excludes: Tests/Curtz/Info.plist
        createIntermediateGroups: true
    dependencies:
      - target: Curtz_macOS
        link: true
  CurtzAllTests:
    type: framework
    platform: macOS
    deploymentTarget: 12.6
    info:
      path: Tests/CurtzAllTests/info.plist
    codesign: false
    dependencies:
      - target: Curtz_macOS
        link: true
    scheme:
      gatherCoverageData: true
      testTargets:
        - name: CurtzUnitTests
          parallelizable: false
          randomExecutionOrder: true
      coverageTargets: [Curtz_macOS]
  CurtziOSApp:
    type: application
    platform: iOS
    deploymentTarget: 16.0
    lifecycle: SwiftUI App
    interface: SwiftUI
    info:
      path: Sources/CurtziOSApp/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleName: CurtziOSApp
        UIRequiredDeviceCapabilities: [armv7]
        UILaunchStoryboardName: LaunchScreen
    settings:
      INFOPLIST_FILE: Sources/CurtziOSApp/Info.plist
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.backbase.SecureStorageTestApp
        SUPPORTS_MACCATALYST: NO
        MARKETING_VERSION: 0.0.1
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_ENTITLEMENTS: ${codeSignEntitlements}
    sources: 
      - path: Sources/CurtziOSApp
        excludes: Sources/CurtziOSApp/Info.plist
        createIntermediateGroups: true
    dependencies:
      - target: Curtz_iOS


#TODO
# Remove curtz framework [iOS, macOS] so that it can be as generic as possible since it'll not contain any platform specific code
#  Then -> Update Curtz_iOS to Curtz
#  Then -> Update Curtz_macOS to Curtz